// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace IntegrationTest.Net7.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Advanced E-commerce Order Processing")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [NUnit.Framework.CategoryAttribute("api")]
    [NUnit.Framework.CategoryAttribute("integration")]
    [NUnit.Framework.CategoryAttribute("high-priority")]
    public partial class AdvancedE_CommerceOrderProcessingFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "api",
                "integration",
                "high-priority"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Advanced E-commerce Order Processing", "  As a customer\n  I want to place orders with various payment methods and shippin" +
                "g options\n  So that I can receive my products conveniently", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "advanced_ecommerce.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 12
  #line hidden
#line 13
    await testRunner.GivenAsync("the e-commerce platform is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Product ID",
                        "Name",
                        "Price",
                        "Stock",
                        "Category"});
            table1.AddRow(new string[] {
                        "PROD-001",
                        "Laptop Pro 15\"",
                        "999.99",
                        "50",
                        "Electronics"});
            table1.AddRow(new string[] {
                        "PROD-002",
                        "Wireless Mouse",
                        "29.99",
                        "200",
                        "Accessories"});
            table1.AddRow(new string[] {
                        "PROD-003",
                        "USB-C Cable",
                        "14.99",
                        "500",
                        "Accessories"});
            table1.AddRow(new string[] {
                        "PROD-004",
                        "4K Monitor",
                        "499.99",
                        "30",
                        "Electronics"});
            table1.AddRow(new string[] {
                        "PROD-005",
                        "Mechanical Keyboard",
                        "89.99",
                        "75",
                        "Accessories"});
#line 14
    await testRunner.AndAsync("the following products are available in inventory:", ((string)(null)), table1, "And ");
#line hidden
#line 21
    await testRunner.AndAsync("the payment gateway is online", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.AndAsync("the shipping service is available", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Complete order with credit card and express shipping")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        public async global::System.Threading.Tasks.Task CompleteOrderWithCreditCardAndExpressShipping()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "checkout"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Complete order with credit card and express shipping", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.GivenAsync("I am logged in as \"premium.customer@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Product ID",
                            "Quantity"});
                table2.AddRow(new string[] {
                            "PROD-001",
                            "1"});
                table2.AddRow(new string[] {
                            "PROD-002",
                            "2"});
#line 29
    await testRunner.AndAsync("my shopping cart contains:", ((string)(null)), table2, "And ");
#line hidden
#line 33
    await testRunner.WhenAsync("I proceed to checkout", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.AndAsync("I select shipping address:", "John Doe\n123 Main Street, Apt 4B\nSan Francisco, CA 94102\nUnited States", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.AndAsync("I choose \"Express Shipping\" delivery method", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table3.AddRow(new string[] {
                            "Card Number",
                            "4532-1234-5678-9010"});
                table3.AddRow(new string[] {
                            "Expiry Date",
                            "12/2027"});
                table3.AddRow(new string[] {
                            "CVV",
                            "123"});
                table3.AddRow(new string[] {
                            "Billing ZIP",
                            "94102"});
#line 42
    await testRunner.AndAsync("I enter payment details:", ((string)(null)), table3, "And ");
#line hidden
#line 48
    await testRunner.AndAsync("I apply promotional code \"SAVE10\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.AndAsync("I confirm the order", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.ThenAsync("the order should be placed successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
    await testRunner.AndAsync("I should receive order confirmation email", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.AndAsync("the order total should be:", "{\n  \"subtotal\": 1059.97,\n  \"discount\": 106.00,\n  \"shipping\": 25.00,\n  \"tax\": 85.8" +
                        "0,\n  \"total\": 1064.77\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Product ID",
                            "New Stock"});
                table4.AddRow(new string[] {
                            "PROD-001",
                            "49"});
                table4.AddRow(new string[] {
                            "PROD-002",
                            "198"});
#line 62
    await testRunner.AndAsync("the inventory should be updated:", ((string)(null)), table4, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Process orders with different payment methods and customer types")]
        [NUnit.Framework.CategoryAttribute("data-driven")]
        [NUnit.Framework.CategoryAttribute("payment-methods")]
        [NUnit.Framework.TestCaseAttribute("premium", "premium1@example.com", "5000", "PROD-001", "1", "Credit Card", "Express", "confirmed", "email_sms", "6000", "1-2", new string[] {
                "premium-customers"}, Category="premium-customers")]
        [NUnit.Framework.TestCaseAttribute("premium", "premium2@example.com", "3500", "PROD-004", "2", "PayPal", "Express", "confirmed", "email_sms", "4500", "1-2", new string[] {
                "premium-customers"}, Category="premium-customers")]
        [NUnit.Framework.TestCaseAttribute("premium", "premium3@example.com", "10000", "PROD-005", "3", "Apple Pay", "Standard", "confirmed", "email_sms", "10270", "3-5", new string[] {
                "premium-customers"}, Category="premium-customers")]
        [NUnit.Framework.TestCaseAttribute("premium", "vip@example.com", "25000", "PROD-001", "5", "Credit Card", "Same Day", "confirmed", "email_sms_push", "30000", "same-day", new string[] {
                "premium-customers"}, Category="premium-customers")]
        [NUnit.Framework.TestCaseAttribute("regular", "user1@example.com", "100", "PROD-002", "1", "Credit Card", "Standard", "confirmed", "email", "130", "3-5", new string[] {
                "regular-customers"}, Category="regular-customers")]
        [NUnit.Framework.TestCaseAttribute("regular", "user2@example.com", "0", "PROD-003", "5", "Debit Card", "Standard", "confirmed", "email", "75", "3-5", new string[] {
                "regular-customers"}, Category="regular-customers")]
        [NUnit.Framework.TestCaseAttribute("regular", "user3@example.com", "500", "PROD-005", "1", "PayPal", "Economy", "confirmed", "email", "590", "5-7", new string[] {
                "regular-customers"}, Category="regular-customers")]
        [NUnit.Framework.TestCaseAttribute("regular", "failcard@example.com", "200", "PROD-001", "1", "Credit Card", "Express", "failed", "error", "200", "N/A", new string[] {
                "edge-cases"}, Category="edge-cases")]
        [NUnit.Framework.TestCaseAttribute("guest", "guest@example.com", "0", "PROD-003", "100", "Credit Card", "Standard", "pending", "email", "0", "3-5", new string[] {
                "edge-cases"}, Category="edge-cases")]
        [NUnit.Framework.TestCaseAttribute("suspended", "suspended@example.com", "1000", "PROD-002", "1", "Credit Card", "Express", "rejected", "error", "1000", "N/A", new string[] {
                "edge-cases"}, Category="edge-cases")]
        public async global::System.Threading.Tasks.Task ProcessOrdersWithDifferentPaymentMethodsAndCustomerTypes(string customer_Type, string email, string loyalty_Points, string product_Id, string quantity, string payment_Method, string shipping_Method, string order_Status, string notification_Type, string final_Points, string delivery_Days, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "data-driven",
                    "payment-methods"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("customer_type", customer_Type);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("loyalty_points", loyalty_Points);
            argumentsOfScenario.Add("product_id", product_Id);
            argumentsOfScenario.Add("quantity", quantity);
            argumentsOfScenario.Add("payment_method", payment_Method);
            argumentsOfScenario.Add("shipping_method", shipping_Method);
            argumentsOfScenario.Add("order_status", order_Status);
            argumentsOfScenario.Add("notification_type", notification_Type);
            argumentsOfScenario.Add("final_points", final_Points);
            argumentsOfScenario.Add("delivery_days", delivery_Days);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process orders with different payment methods and customer types", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 70
    await testRunner.GivenAsync(string.Format("I am logged in as a \"{0}\" customer with email \"{1}\"", customer_Type, email), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
    await testRunner.AndAsync(string.Format("I have \"{0}\" loyalty points", loyalty_Points), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.WhenAsync(string.Format("I add product \"{0}\" with quantity {1} to cart", product_Id, quantity), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.AndAsync(string.Format("I proceed to checkout with \"{0}\" payment", payment_Method), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.AndAsync(string.Format("I select \"{0}\" shipping", shipping_Method), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.ThenAsync(string.Format("the order should be \"{0}\"", order_Status), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 76
    await testRunner.AndAsync(string.Format("I should see \"{0}\" notification", notification_Type), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync(string.Format("my loyalty points should be \"{0}\"", final_Points), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync(string.Format("the estimated delivery should be within \"{0}\" days", delivery_Days), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Process large wholesale order with custom pricing")]
        [NUnit.Framework.CategoryAttribute("bulk-order")]
        [NUnit.Framework.CategoryAttribute("wholesale")]
        public async global::System.Threading.Tasks.Task ProcessLargeWholesaleOrderWithCustomPricing()
        {
            string[] tagsOfScenario = new string[] {
                    "bulk-order",
                    "wholesale"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process large wholesale order with custom pricing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 108
    await testRunner.GivenAsync("I am logged in as a \"wholesale\" customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
    await testRunner.AndAsync("I have negotiated pricing agreement \"WHOLESALE-2025-A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "SKU",
                            "Product Name",
                            "Quantity",
                            "Unit Price",
                            "Total Price"});
                table5.AddRow(new string[] {
                            "PROD-001",
                            "Laptop Pro 15\"",
                            "50",
                            "899.99",
                            "44999.50"});
                table5.AddRow(new string[] {
                            "PROD-002",
                            "Wireless Mouse",
                            "200",
                            "24.99",
                            "4998.00"});
                table5.AddRow(new string[] {
                            "PROD-003",
                            "USB-C Cable",
                            "500",
                            "12.99",
                            "6495.00"});
                table5.AddRow(new string[] {
                            "PROD-004",
                            "4K Monitor",
                            "30",
                            "449.99",
                            "13499.70"});
                table5.AddRow(new string[] {
                            "PROD-005",
                            "Mechanical Keyboard",
                            "100",
                            "79.99",
                            "7999.00"});
                table5.AddRow(new string[] {
                            "PROD-006",
                            "Laptop Stand",
                            "75",
                            "39.99",
                            "2999.25"});
                table5.AddRow(new string[] {
                            "PROD-007",
                            "Webcam HD",
                            "150",
                            "69.99",
                            "10498.50"});
                table5.AddRow(new string[] {
                            "PROD-008",
                            "Headset Pro",
                            "200",
                            "89.99",
                            "17998.00"});
                table5.AddRow(new string[] {
                            "PROD-009",
                            "External SSD 1TB",
                            "100",
                            "119.99",
                            "11999.00"});
                table5.AddRow(new string[] {
                            "PROD-010",
                            "Dock Station",
                            "50",
                            "199.99",
                            "9999.50"});
#line 110
    await testRunner.WhenAsync("I create a bulk order with the following items:", ((string)(null)), table5, "When ");
#line hidden
#line 122
    await testRunner.AndAsync("I request split shipment to multiple warehouses:", "Warehouse 1 (West Coast):\n  - 60% of items to San Francisco, CA\nWarehouse 2 (East" +
                        " Coast):\n  - 40% of items to New York, NY\n\nDelivery Instructions:\n  - Signature " +
                        "required\n  - Business hours only (9 AM - 5 PM)\n  - Loading dock access needed", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
    await testRunner.AndAsync("I choose payment terms \"Net 30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
    await testRunner.ThenAsync("the order should be submitted for approval", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 136
    await testRunner.AndAsync("I should receive quote document with order ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
    await testRunner.AndAsync("the estimated total should be \"$131485.45\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
    await testRunner.AndAsync("the bulk discount should be \"15%\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.AndAsync("the final amount should be \"$111762.63\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Process return with partial refund and restocking")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("returns")]
        [NUnit.Framework.CategoryAttribute("refund")]
        public async global::System.Threading.Tasks.Task ProcessReturnWithPartialRefundAndRestocking()
        {
            string[] tagsOfScenario = new string[] {
                    "returns",
                    "refund",
                    "ignore"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process return with partial refund and restocking", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 142
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 143
    await testRunner.GivenAsync("I have an existing order \"ORD-2025-12345\" with status \"delivered\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 144
    await testRunner.AndAsync("the order was delivered 5 days ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Product ID",
                            "Product Name",
                            "Quantity",
                            "Price",
                            "Status"});
                table6.AddRow(new string[] {
                            "PROD-001",
                            "Laptop Pro 15\"",
                            "1",
                            "999.99",
                            "delivered"});
                table6.AddRow(new string[] {
                            "PROD-002",
                            "Wireless Mouse",
                            "2",
                            "29.99",
                            "delivered"});
                table6.AddRow(new string[] {
                            "PROD-003",
                            "USB-C Cable",
                            "1",
                            "14.99",
                            "delivered"});
#line 145
    await testRunner.AndAsync("the order contained:", ((string)(null)), table6, "And ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Product ID",
                            "Quantity",
                            "Reason",
                            "Condition"});
                table7.AddRow(new string[] {
                            "PROD-001",
                            "1",
                            "Defective screen",
                            "Damaged"});
                table7.AddRow(new string[] {
                            "PROD-002",
                            "1",
                            "Changed mind",
                            "Unopened"});
#line 150
    await testRunner.WhenAsync("I initiate a return for the following items:", ((string)(null)), table7, "When ");
#line hidden
#line 154
    await testRunner.AndAsync("I upload return images:", "- laptop_screen_defect.jpg\n- mouse_unopened_box.jpg\n- shipping_label.pdf", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
    await testRunner.AndAsync("I select refund method \"Original Payment Method\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
    await testRunner.ThenAsync("the return request should be approved", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 162
    await testRunner.AndAsync("I should receive return shipping label via email", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Item",
                            "Amount",
                            "Restocking Fee",
                            "Refund Amount"});
                table8.AddRow(new string[] {
                            "Laptop Pro 15\"",
                            "999.99",
                            "0.00",
                            "999.99"});
                table8.AddRow(new string[] {
                            "Wireless Mouse",
                            "29.99",
                            "3.00",
                            "26.99"});
                table8.AddRow(new string[] {
                            "Processing Fee",
                            "-",
                            "-",
                            "-10.00"});
                table8.AddRow(new string[] {
                            "Total Refund",
                            "-",
                            "-",
                            "1016.98"});
#line 163
    await testRunner.AndAsync("the refund amount should be calculated as:", ((string)(null)), table8, "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Product ID",
                            "Increment",
                            "New Status"});
                table9.AddRow(new string[] {
                            "PROD-001",
                            "0",
                            "quarantine"});
                table9.AddRow(new string[] {
                            "PROD-002",
                            "1",
                            "available"});
#line 169
    await testRunner.AndAsync("the inventory should be incremented:", ((string)(null)), table9, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Setup recurring monthly subscription order")]
        [NUnit.Framework.CategoryAttribute("subscription")]
        [NUnit.Framework.CategoryAttribute("recurring")]
        public async global::System.Threading.Tasks.Task SetupRecurringMonthlySubscriptionOrder()
        {
            string[] tagsOfScenario = new string[] {
                    "subscription",
                    "recurring"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Setup recurring monthly subscription order", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 175
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 177
    await testRunner.GivenAsync("I am logged in as \"subscriber@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 178
    await testRunner.WhenAsync("I choose a subscription plan with the following configuration:", @"subscription_type: monthly
products:
  - product_id: PROD-003
    quantity: 5
    frequency: every_month
  - product_id: PROD-002
    quantity: 2
    frequency: every_month
billing:
  payment_method: Credit Card
  billing_day: 1st of month
shipping:
  method: Standard
  address: Same as account
discounts:
  - type: subscription_discount
    amount: 20%
  - type: loyalty_bonus
    amount: 5%
notifications:
  - email: 3 days before charge
  - sms: on shipment", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 203
    await testRunner.AndAsync("I confirm subscription terms and conditions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
    await testRunner.ThenAsync("the subscription should be activated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table10.AddRow(new string[] {
                            "Status",
                            "Active"});
                table10.AddRow(new string[] {
                            "Next Billing Date",
                            "2025-01-01"});
                table10.AddRow(new string[] {
                            "Monthly Amount",
                            "$127.48"});
                table10.AddRow(new string[] {
                            "Products per Month",
                            "7 items"});
                table10.AddRow(new string[] {
                            "Savings per Order",
                            "$31.87 (25%)"});
                table10.AddRow(new string[] {
                            "Cancellation Policy",
                            "Cancel anytime"});
#line 205
    await testRunner.AndAsync("I should see subscription dashboard with:", ((string)(null)), table10, "And ");
#line hidden
#line 213
    await testRunner.AndAsync("I should receive welcome email with subscription details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 214
    await testRunner.AndAsync("a calendar reminder should be created for \"2024-12-29\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
