// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace IntegrationTest.Net8.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("User Management REST API")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("api")]
    [global::NUnit.Framework.CategoryAttribute("rest")]
    [global::NUnit.Framework.CategoryAttribute("backend")]
    public partial class UserManagementRESTAPIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "api",
                "rest",
                "backend"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "User Management REST API", "  As an API consumer\n  I want to manage user accounts via REST endpoints\n  So tha" +
                "t I can integrate with the user management system", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "api_testing.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 11
  #line hidden
#line 12
    await testRunner.GivenAsync("the API base URL is \"https://api.example.com/v2\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
            global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                        "Key",
                        "Value"});
            table11.AddRow(new string[] {
                        "API_KEY",
                        "test_api_key_1234567890abcdef"});
            table11.AddRow(new string[] {
                        "API_SECRET",
                        "test_api_secret_0987654321fedcba"});
#line 13
    await testRunner.AndAsync("I have valid API credentials:", ((string)(null)), table11, "And ");
#line hidden
#line 17
    await testRunner.AndAsync("the API rate limit is 1000 requests per hour", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                        "Header",
                        "Value"});
            table12.AddRow(new string[] {
                        "Content-Type",
                        "application/json"});
            table12.AddRow(new string[] {
                        "Accept",
                        "application/json"});
#line 18
    await testRunner.AndAsync("I set request headers:", ((string)(null)), table12, "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/api_testing.feature.ndjson", 23);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create new user account via API")]
        [global::NUnit.Framework.CategoryAttribute("crud")]
        [global::NUnit.Framework.CategoryAttribute("post")]
        public async global::System.Threading.Tasks.Task CreateNewUserAccountViaAPI()
        {
            string[] tagsOfScenario = new string[] {
                    "crud",
                    "post"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create new user account via API", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.WhenAsync("I send a POST request to \"/users\" with body:", @"{
  ""username"": ""john.doe.2025"",
  ""email"": ""john.doe@example.com"",
  ""firstName"": ""John"",
  ""lastName"": ""Doe"",
  ""password"": ""SecureP@ssw0rd!"",
  ""dateOfBirth"": ""1990-05-15"",
  ""phoneNumber"": ""+1-555-123-4567"",
  ""address"": {
    ""street"": ""123 Main St"",
    ""city"": ""San Francisco"",
    ""state"": ""CA"",
    ""zipCode"": ""94102"",
    ""country"": ""USA""
  },
  ""preferences"": {
    ""newsletter"": true,
    ""smsNotifications"": false,
    ""theme"": ""dark""
  },
  ""roles"": [""user"", ""customer""],
  ""metadata"": {
    ""source"": ""mobile_app"",
    ""campaign"": ""spring_2025""
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the response status code should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.AndAsync("the response time should be less than 500 milliseconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("the response should have header \"Location\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.AndAsync("the response body should match:", @"{
  ""id"": ""@uuid@"",
  ""username"": ""john.doe.2025"",
  ""email"": ""john.doe@example.com"",
  ""firstName"": ""John"",
  ""lastName"": ""Doe"",
  ""status"": ""active"",
  ""emailVerified"": false,
  ""createdAt"": ""@datetime@"",
  ""updatedAt"": ""@datetime@"",
  ""_links"": {
    ""self"": ""/users/@string@"",
    ""verify-email"": ""/users/@string@/verify"",
    ""update"": ""/users/@string@""
  }
}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync("the response should NOT contain field \"password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync("I should receive webhook notification:", "{\n  \"event\": \"user.created\",\n  \"userId\": \"@uuid@\",\n  \"timestamp\": \"@datetime@\"\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validate user creation with invalid data")]
        [global::NUnit.Framework.CategoryAttribute("validation")]
        [global::NUnit.Framework.CategoryAttribute("negative")]
        [global::NUnit.Framework.TestCaseAttribute("", "valid@example.com", "Pass123!", "400", "MISSING_FIELD", "Username is required", "username", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("john", "invalid-email", "Pass123!", "400", "INVALID_FORMAT", "Invalid email format", "email", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("john", "valid@example.com", "123", "400", "WEAK_PASSWORD", "Password must be at least 8 characters", "password", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("ab", "valid@example.com", "Pass123!", "400", "TOO_SHORT", "Username must be at least 3 characters", "username", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("john", "duplicate@example.com", "Pass123!", "409", "DUPLICATE_USER", "Email already exists", "email", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("$pecial#", "valid@example.com", "Pass123!", "400", "INVALID_CHARACTERS", "Username contains invalid characters", "username", "6", null)]
        public async global::System.Threading.Tasks.Task ValidateUserCreationWithInvalidData(string username, string email, string password, string status_Code, string error_Code, string error_Message, string field, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "validation",
                    "negative"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("status_code", status_Code);
            argumentsOfScenario.Add("error_code", error_Code);
            argumentsOfScenario.Add("error_message", error_Message);
            argumentsOfScenario.Add("field", field);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate user creation with invalid data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 88
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 89
    await testRunner.WhenAsync("I send a POST request to \"/users\" with body:", string.Format("{{\n  \"username\": \"{0}\",\n  \"email\": \"{1}\",\n  \"password\": \"{2}\"\n}}", username, email, password), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
    await testRunner.ThenAsync(string.Format("the response status code should be {0}", status_Code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
    await testRunner.AndAsync("the response body should contain error:", string.Format("{{\n  \"error\": {{\n    \"code\": \"{0}\",\n    \"message\": \"{1}\",\n    \"field\": \"{2}\"\n  }}" +
                            "\n}}", error_Code, error_Message, field), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Retrieve paginated list of users")]
        [global::NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [global::NUnit.Framework.CategoryAttribute("crud")]
        [global::NUnit.Framework.CategoryAttribute("get")]
        [global::NUnit.Framework.CategoryAttribute("pagination")]
        public async global::System.Threading.Tasks.Task RetrievePaginatedListOfUsers()
        {
            string[] tagsOfScenario = new string[] {
                    "crud",
                    "get",
                    "pagination",
                    "ignore"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retrieve paginated list of users", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 119
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 120
    await testRunner.GivenAsync("the database contains 150 users", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table13.AddRow(new string[] {
                            "page",
                            "2"});
                table13.AddRow(new string[] {
                            "limit",
                            "25"});
                table13.AddRow(new string[] {
                            "sort",
                            "email"});
                table13.AddRow(new string[] {
                            "order",
                            "asc"});
                table13.AddRow(new string[] {
                            "status",
                            "active"});
#line 121
    await testRunner.WhenAsync("I send a GET request to \"/users\" with query parameters:", ((string)(null)), table13, "When ");
#line hidden
#line 128
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 129
    await testRunner.AndAsync("the response should contain 25 users", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
    await testRunner.AndAsync("the response should have pagination metadata:", @"{
  ""pagination"": {
    ""page"": 2,
    ""limit"": 25,
    ""total"": 150,
    ""totalPages"": 6,
    ""hasNext"": true,
    ""hasPrevious"": true,
    ""links"": {
      ""first"": ""/users?page=1&limit=25"",
      ""previous"": ""/users?page=1&limit=25"",
      ""next"": ""/users?page=3&limit=25"",
      ""last"": ""/users?page=6&limit=25""
    }
  }
}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
    await testRunner.AndAsync("all users should have \"active\" status", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 150
    await testRunner.AndAsync("the users should be sorted by \"email\" in \"ascending\" order", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Partially update user profile")]
        [global::NUnit.Framework.CategoryAttribute("crud")]
        [global::NUnit.Framework.CategoryAttribute("patch")]
        [global::NUnit.Framework.CategoryAttribute("partial-update")]
        public async global::System.Threading.Tasks.Task PartiallyUpdateUserProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "crud",
                    "patch",
                    "partial-update"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Partially update user profile", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 153
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 154
    await testRunner.GivenAsync("a user exists with ID \"usr_abc123xyz\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 155
    await testRunner.WhenAsync("I send a PATCH request to \"/users/usr_abc123xyz\" with body:", "{\n  \"phoneNumber\": \"+1-555-999-8888\",\n  \"preferences\": {\n    \"newsletter\": false," +
                        "\n    \"theme\": \"light\"\n  }\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 165
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table14.AddRow(new string[] {
                            "phoneNumber",
                            "+1-555-999-8888"});
                table14.AddRow(new string[] {
                            "preferences.newsletter",
                            "false"});
                table14.AddRow(new string[] {
                            "preferences.theme",
                            "light"});
#line 166
    await testRunner.AndAsync("the response should contain updated fields:", ((string)(null)), table14, "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Field"});
                table15.AddRow(new string[] {
                            "email"});
                table15.AddRow(new string[] {
                            "username"});
                table15.AddRow(new string[] {
                            "firstName"});
                table15.AddRow(new string[] {
                            "lastName"});
#line 171
    await testRunner.AndAsync("the response should preserve original values:", ((string)(null)), table15, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Soft delete user account")]
        [global::NUnit.Framework.CategoryAttribute("crud")]
        [global::NUnit.Framework.CategoryAttribute("delete")]
        [global::NUnit.Framework.CategoryAttribute("soft-delete")]
        public async global::System.Threading.Tasks.Task SoftDeleteUserAccount()
        {
            string[] tagsOfScenario = new string[] {
                    "crud",
                    "delete",
                    "soft-delete"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Soft delete user account", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 179
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 180
    await testRunner.GivenAsync("a user exists with email \"delete.me@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 181
    await testRunner.WhenAsync("I send a DELETE request to \"/users/{userId}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 182
    await testRunner.ThenAsync("the response status code should be 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 183
    await testRunner.AndAsync("the user should be marked as \"deleted\" in database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
    await testRunner.AndAsync("the user should NOT appear in GET \"/users\" response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
    await testRunner.AndAsync("the user data should be retained for 30 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
    await testRunner.AndAsync("I should receive deletion confirmation email", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Bulk update user roles")]
        [global::NUnit.Framework.CategoryAttribute("batch")]
        [global::NUnit.Framework.CategoryAttribute("bulk-operations")]
        public async global::System.Threading.Tasks.Task BulkUpdateUserRoles()
        {
            string[] tagsOfScenario = new string[] {
                    "batch",
                    "bulk-operations"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bulk update user roles", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 189
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 190
    await testRunner.WhenAsync("I send a POST request to \"/users/bulk/update-roles\" with body:", "{\n  \"userIds\": [\n    \"usr_001\",\n    \"usr_002\",\n    \"usr_003\",\n    \"usr_004\",\n    " +
                        "\"usr_005\"\n  ],\n  \"action\": \"add\",\n  \"roles\": [\"premium\", \"beta-tester\"]\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 204
    await testRunner.ThenAsync("the response status code should be 202", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 205
    await testRunner.AndAsync("the response should contain batch job information:", "{\n  \"jobId\": \"@uuid@\",\n  \"status\": \"processing\",\n  \"totalUsers\": 5,\n  \"estimatedC" +
                        "ompletion\": \"@datetime@\",\n  \"statusUrl\": \"/jobs/@string@\"\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 215
    await testRunner.AndAsync("within 10 seconds the job status should be \"completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
    await testRunner.AndAsync("all 5 users should have roles [\"user\", \"customer\", \"premium\", \"beta-tester\"]", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Test API authentication and authorization")]
        [global::NUnit.Framework.CategoryAttribute("security")]
        [global::NUnit.Framework.CategoryAttribute("authentication")]
        [global::NUnit.Framework.TestCaseAttribute("GET", "/users", "valid_token", "200", "users", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("GET", "/users", "expired_token", "401", "error", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("GET", "/users", "invalid_token", "401", "error", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("GET", "/users", "no_token", "401", "error", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("GET", "/admin/users", "user_token", "403", "error", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("GET", "/admin/users", "admin_token", "200", "users", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("POST", "/users", "valid_token", "201", "id", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("DELETE", "/users/usr_123", "other_user", "403", "error", "18", null)]
        public async global::System.Threading.Tasks.Task TestAPIAuthenticationAndAuthorization(string method, string endpoint, string auth_Type, string status_Code, string response_Field, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "security",
                    "authentication"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("method", method);
            argumentsOfScenario.Add("endpoint", endpoint);
            argumentsOfScenario.Add("auth_type", auth_Type);
            argumentsOfScenario.Add("status_code", status_Code);
            argumentsOfScenario.Add("response_field", response_Field);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Test API authentication and authorization", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 219
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 220
    await testRunner.WhenAsync(string.Format("I send a {0} request to \"{1}\" with authentication \"{2}\"", method, endpoint, auth_Type), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 221
    await testRunner.ThenAsync(string.Format("the response status code should be {0}", status_Code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 222
    await testRunner.AndAsync(string.Format("the response should contain \"{0}\"", response_Field), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("API should handle concurrent requests efficiently")]
        [global::NUnit.Framework.CategoryAttribute("performance")]
        [global::NUnit.Framework.CategoryAttribute("load-testing")]
        public async global::System.Threading.Tasks.Task APIShouldHandleConcurrentRequestsEfficiently()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "load-testing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("API should handle concurrent requests efficiently", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 236
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 238
    await testRunner.WhenAsync("I send 100 concurrent GET requests to \"/users/{randomUserId}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 239
    await testRunner.ThenAsync("at least 95% of requests should complete within 1 second", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 240
    await testRunner.AndAsync("the average response time should be less than 300 milliseconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 241
    await testRunner.AndAsync("no requests should fail due to rate limiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 242
    await testRunner.AndAsync("the API should return correct data in all responses", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify webhook delivery for user events")]
        [global::NUnit.Framework.CategoryAttribute("webhooks")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task VerifyWebhookDeliveryForUserEvents()
        {
            string[] tagsOfScenario = new string[] {
                    "webhooks",
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify webhook delivery for user events", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 245
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 246
    await testRunner.GivenAsync("I have configured a webhook endpoint \"https://myapp.com/webhooks/users\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 247
    await testRunner.AndAsync("the webhook signature secret is \"whsec_test_secret_key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 248
    await testRunner.WhenAsync("I create a new user via API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 249
    await testRunner.ThenAsync("a webhook POST request should be sent to my endpoint within 5 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 250
    await testRunner.AndAsync("the webhook payload should contain:", "{\n  \"id\": \"@uuid@\",\n  \"event\": \"user.created\",\n  \"apiVersion\": \"v2\",\n  \"timestamp" +
                        "\": \"@datetime@\",\n  \"data\": {\n    \"userId\": \"@uuid@\",\n    \"username\": \"@string@\"," +
                        "\n    \"email\": \"@email@\"\n  }\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 264
    await testRunner.AndAsync("the webhook request should include header \"X-Webhook-Signature\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 265
    await testRunner.AndAsync("the signature should be valid using HMAC-SHA256", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 266
    await testRunner.AndAsync("if webhook fails, it should retry 3 times with exponential backoff", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
