// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace IntegrationTest.Net8.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Complete Gherkin Syntax Demonstration")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("gherkin-showcase")]
    [global::NUnit.Framework.CategoryAttribute("complete-syntax")]
    public partial class CompleteGherkinSyntaxDemonstrationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "gherkin-showcase",
                "complete-syntax"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Complete Gherkin Syntax Demonstration", @"  This feature demonstrates all possible Gherkin keywords and constructs
  including comments, tags, backgrounds, scenarios, scenario outlines,
  data tables, doc strings, and various step keywords.
  
  It serves as a comprehensive test case for the Universal BDD Parser
  to ensure all Gherkin elements are correctly parsed and represented.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "complete_gherkin_syntax.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/complete_gherkin_syntax.feature.ndjson", 22);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Successful login with valid credentials")]
        [global::NUnit.Framework.CategoryAttribute("positive")]
        [global::NUnit.Framework.CategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task SuccessfulLoginWithValidCredentials()
        {
            string[] tagsOfScenario = new string[] {
                    "positive",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful login with valid credentials", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("User Authentication Rules", "    All users must be authenticated before accessing protected resources\n    Auth" +
                    "entication can be via username/password, OAuth, or API keys", tagsOfRule);
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
      await testRunner.GivenAsync("the authentication service is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
      await testRunner.AndAsync("the user database is accessible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
      await testRunner.AndAsync("rate limiting is configured to 5 attempts per minute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
      await testRunner.AndAsync("logging is enabled for security events", ((string)(null)), ((global::Reqnroll.Table)(null)), "* ");
#line hidden
#line 30
      await testRunner.GivenAsync("a user exists with username \"john_doe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
      await testRunner.AndAsync("the user\'s password is \"SecurePass123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
      await testRunner.AndAsync("the user\'s account is \"active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
      await testRunner.AndAsync("the user has role \"standard_user\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
      await testRunner.AndAsync("the user\'s email is verified", ((string)(null)), ((global::Reqnroll.Table)(null)), "* ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table16.AddRow(new string[] {
                            "username",
                            "john_doe"});
                table16.AddRow(new string[] {
                            "password",
                            "SecurePass123!"});
#line 37
      await testRunner.WhenAsync("the user submits login form with:", ((string)(null)), table16, "When ");
#line hidden
#line 41
      await testRunner.AndAsync("the user\'s IP address is \"192.168.1.100\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
      await testRunner.AndAsync("the user agent is \"Mozilla/5.0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
      await testRunner.AndAsync("the request includes CSRF token", ((string)(null)), ((global::Reqnroll.Table)(null)), "* ");
#line hidden
#line 46
      await testRunner.ThenAsync("the login should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
      await testRunner.AndAsync("a session token should be generated", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
      await testRunner.AndAsync("the session should expire in 30 minutes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
      await testRunner.ButAsync("the password should NOT be logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
#line 50
      await testRunner.AndAsync("an audit entry should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "* ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Failed login attempts should trigger account lockout")]
        [global::NUnit.Framework.CategoryAttribute("negative")]
        [global::NUnit.Framework.CategoryAttribute("security")]
        public async global::System.Threading.Tasks.Task FailedLoginAttemptsShouldTriggerAccountLockout()
        {
            string[] tagsOfScenario = new string[] {
                    "negative",
                    "security"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Failed login attempts should trigger account lockout", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("User Authentication Rules", "    All users must be authenticated before accessing protected resources\n    Auth" +
                    "entication can be via username/password, OAuth, or API keys", tagsOfRule);
#line 53
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
      await testRunner.GivenAsync("the authentication service is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
      await testRunner.AndAsync("the user database is accessible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
      await testRunner.AndAsync("rate limiting is configured to 5 attempts per minute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
      await testRunner.AndAsync("logging is enabled for security events", ((string)(null)), ((global::Reqnroll.Table)(null)), "* ");
#line hidden
#line 54
      await testRunner.GivenAsync("a user exists with username \"jane_doe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
      await testRunner.AndAsync("the account lockout threshold is 3 attempts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
      await testRunner.WhenAsync("the user enters wrong password 3 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
      await testRunner.ThenAsync("the account should be locked", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
      await testRunner.AndAsync("the user should see error message:", "Your account has been temporarily locked due to multiple failed login attempts.\nP" +
                        "lease try again in 15 minutes or reset your password.\n\nFor security reasons, we\'" +
                        "ve sent an email notification to your registered address.", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
      await testRunner.AndAsync("an email should be sent with subject \"Security Alert: Account Locked\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
      await testRunner.ButAsync("the actual password should NOT be revealed", ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Login with different user roles and permissions")]
        [global::NUnit.Framework.CategoryAttribute("data-driven")]
        [global::NUnit.Framework.CategoryAttribute("parametrized")]
        [global::NUnit.Framework.TestCaseAttribute("admin_001", "super_admin", "all", "none", "admin_full_menu", "2", new string[] {
                "admin-users"}, Category="admin-users")]
        [global::NUnit.Framework.TestCaseAttribute("admin_002", "admin", "dashboard,users,settings,reports", "system_config", "admin_menu", "3", new string[] {
                "admin-users"}, Category="admin-users")]
        [global::NUnit.Framework.TestCaseAttribute("moderator", "moderator", "dashboard,content,reports", "users,settings", "moderator_menu", "4", new string[] {
                "admin-users"}, Category="admin-users")]
        [global::NUnit.Framework.TestCaseAttribute("user_001", "premium", "dashboard,profile,content,premium", "admin,settings", "premium_user_menu", "5", new string[] {
                "regular-users"}, Category="regular-users")]
        [global::NUnit.Framework.TestCaseAttribute("user_002", "standard", "dashboard,profile,content", "admin,settings,premium", "standard_user_menu", "6", new string[] {
                "regular-users"}, Category="regular-users")]
        [global::NUnit.Framework.TestCaseAttribute("user_003", "trial", "dashboard,profile", "content,admin,settings", "trial_user_menu", "7", new string[] {
                "regular-users"}, Category="regular-users")]
        [global::NUnit.Framework.TestCaseAttribute("guest_001", "guest", "public_pages", "all_protected", "guest_menu", "8", new string[] {
                "regular-users"}, Category="regular-users")]
        [global::NUnit.Framework.TestCaseAttribute("suspended", "suspended", "none", "all", "empty", "9", new string[] {
                "edge-cases"}, Category="edge-cases")]
        [global::NUnit.Framework.TestCaseAttribute("readonly", "read_only", "dashboard,reports", "write_operations", "readonly_menu", "10", new string[] {
                "edge-cases"}, Category="edge-cases")]
        public async global::System.Threading.Tasks.Task LoginWithDifferentUserRolesAndPermissions(string username, string role, string accessible_Pages, string restricted_Pages, string navigation_Menu, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "data-driven",
                    "parametrized"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("role", role);
            argumentsOfScenario.Add("accessible_pages", accessible_Pages);
            argumentsOfScenario.Add("restricted_pages", restricted_Pages);
            argumentsOfScenario.Add("navigation_menu", navigation_Menu);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login with different user roles and permissions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("User Authentication Rules", "    All users must be authenticated before accessing protected resources\n    Auth" +
                    "entication can be via username/password, OAuth, or API keys", tagsOfRule);
#line 70
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
      await testRunner.GivenAsync("the authentication service is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
      await testRunner.AndAsync("the user database is accessible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
      await testRunner.AndAsync("rate limiting is configured to 5 attempts per minute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
      await testRunner.AndAsync("logging is enabled for security events", ((string)(null)), ((global::Reqnroll.Table)(null)), "* ");
#line hidden
#line 71
      await testRunner.GivenAsync(string.Format("a user with username \"{0}\" and role \"{1}\"", username, role), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
      await testRunner.WhenAsync("the user logs in successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
      await testRunner.ThenAsync(string.Format("the user should have access to \"{0}\"", accessible_Pages), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
      await testRunner.AndAsync(string.Format("the user should NOT have access to \"{0}\"", restricted_Pages), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
      await testRunner.ButAsync(string.Format("the user should see \"{0}\"", navigation_Menu), ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
#line 76
      await testRunner.AndAsync(string.Format("the session data should include role \"{0}\"", role), ((string)(null)), ((global::Reqnroll.Table)(null)), "* ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Password must meet complexity requirements")]
        public async global::System.Threading.Tasks.Task PasswordMustMeetComplexityRequirements()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Password must meet complexity requirements", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Password Management Rules", "    Passwords must meet security requirements\n    Users can reset forgotten passw" +
                    "ords via email", tagsOfRule);
#line 106
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
      await testRunner.WhenAsync("a user attempts to set password \"<password>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
      await testRunner.ThenAsync("the system should evaluate password strength", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Criteria",
                            "Status",
                            "Details"});
                table17.AddRow(new string[] {
                            "Minimum length (8)",
                            "pass",
                            "Password has 12 characters"});
                table17.AddRow(new string[] {
                            "Contains uppercase",
                            "pass",
                            "Contains: A, B, C"});
                table17.AddRow(new string[] {
                            "Contains lowercase",
                            "pass",
                            "Contains: a, b, c"});
                table17.AddRow(new string[] {
                            "Contains numbers",
                            "pass",
                            "Contains: 1, 2, 3"});
                table17.AddRow(new string[] {
                            "Contains special char",
                            "pass",
                            "Contains: !, @, #"});
                table17.AddRow(new string[] {
                            "Not common password",
                            "pass",
                            "Not in breach database"});
                table17.AddRow(new string[] {
                            "Not same as username",
                            "pass",
                            "Different from username"});
#line 110
      await testRunner.AndAsync("the result should be:", ((string)(null)), table17, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("User can reset password via email token")]
        public async global::System.Threading.Tasks.Task UserCanResetPasswordViaEmailToken()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User can reset password via email token", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Password Management Rules", "    Passwords must meet security requirements\n    Users can reset forgotten passw" +
                    "ords via email", tagsOfRule);
#line 120
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 121
      await testRunner.GivenAsync("a user with email \"user@example.com\" forgot their password", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 122
      await testRunner.WhenAsync("the user requests a password reset", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
      await testRunner.ThenAsync("a reset token should be generated with properties:", "{\n  \"token\": \"randomly_generated_64_char_string\",\n  \"expiresIn\": \"15 minutes\",\n  " +
                        "\"usageLimit\": 1,\n  \"userId\": \"user_id_hash\",\n  \"createdAt\": \"2025-12-02T10:30:00" +
                        "Z\",\n  \"ipAddress\": \"192.168.1.100\"\n}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 134
      await testRunner.AndAsync("an email should be sent containing the reset link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
      await testRunner.WhenAsync("the user clicks the reset link within 15 minutes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 136
      await testRunner.AndAsync("enters a new password \"NewSecureP@ss123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
      await testRunner.ThenAsync("the password should be updated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 138
      await testRunner.AndAsync("all existing sessions should be invalidated", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
      await testRunner.ButAsync("the reset token should be marked as used", ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Setup Time-based One-Time Password (TOTP)")]
        [global::NUnit.Framework.CategoryAttribute("mfa")]
        [global::NUnit.Framework.CategoryAttribute("totp")]
        public async global::System.Threading.Tasks.Task SetupTime_BasedOne_TimePasswordTOTP()
        {
            string[] tagsOfScenario = new string[] {
                    "mfa",
                    "totp"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Setup Time-based One-Time Password (TOTP)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Multi-factor Authentication Rules", null, tagsOfRule);
#line 145
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 146
      await testRunner.GivenAsync("a user wants to enable two-factor authentication", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 147
      await testRunner.WhenAsync("the user initiates TOTP setup", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 148
      await testRunner.ThenAsync("the system should generate a secret key", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 149
      await testRunner.AndAsync("display a QR code with data:", "otpauth://totp/MyApp:user@example.com?\nsecret=JBSWY3DPEHPK3PXP&\nissuer=MyApp&\nalg" +
                        "orithm=SHA1&\ndigits=6&\nperiod=30", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Code",
                            "Status",
                            "Used Date"});
                table18.AddRow(new string[] {
                            "ABC-123",
                            "unused",
                            "null"});
                table18.AddRow(new string[] {
                            "DEF-456",
                            "unused",
                            "null"});
                table18.AddRow(new string[] {
                            "GHI-789",
                            "unused",
                            "null"});
                table18.AddRow(new string[] {
                            "JKL-012",
                            "unused",
                            "null"});
                table18.AddRow(new string[] {
                            "MNO-345",
                            "unused",
                            "null"});
                table18.AddRow(new string[] {
                            "PQR-678",
                            "unused",
                            "null"});
                table18.AddRow(new string[] {
                            "STU-901",
                            "unused",
                            "null"});
                table18.AddRow(new string[] {
                            "VWX-234",
                            "unused",
                            "null"});
#line 158
      await testRunner.AndAsync("provide backup codes:", ((string)(null)), table18, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify TOTP codes with time windows")]
        [global::NUnit.Framework.CategoryAttribute("mfa")]
        [global::NUnit.Framework.CategoryAttribute("verification")]
        [global::NUnit.Framework.TestCaseAttribute("user1", "1638360000", "JBSWY3DPEHPK3PXP", "123456", "success", "current", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("user2", "1638360029", "JBSWY3DPEHPK3PXP", "123456", "success", "current", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("user3", "1638360030", "JBSWY3DPEHPK3PXP", "789012", "success", "next", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("user4", "1638359999", "JBSWY3DPEHPK3PXP", "456789", "success", "previous", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("user5", "1638360000", "JBSWY3DPEHPK3PXP", "999999", "failure", "none", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("user6", "1638300000", "JBSWY3DPEHPK3PXP", "123456", "failure", "expired", "19", null)]
        public async global::System.Threading.Tasks.Task VerifyTOTPCodesWithTimeWindows(string username, string timestamp, string secret, string code, string result, string window, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mfa",
                    "verification"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("timestamp", timestamp);
            argumentsOfScenario.Add("secret", secret);
            argumentsOfScenario.Add("code", code);
            argumentsOfScenario.Add("result", result);
            argumentsOfScenario.Add("window", window);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify TOTP codes with time windows", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Multi-factor Authentication Rules", null, tagsOfRule);
#line 170
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 171
      await testRunner.GivenAsync(string.Format("TOTP is enabled for user \"{0}\"", username), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 172
      await testRunner.AndAsync(string.Format("the current timestamp is {0}", timestamp), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
      await testRunner.AndAsync(string.Format("the secret key is \"{0}\"", secret), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
      await testRunner.WhenAsync(string.Format("the user enters TOTP code \"{0}\"", code), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 175
      await testRunner.ThenAsync(string.Format("the verification should be \"{0}\"", result), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 176
      await testRunner.AndAsync(string.Format("the time window used should be \"{0}\"", window), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
